import Navbar from './components/Navbar'
import './globals.css'
import { roboto } from './utils/font'
import { CartProvider } from './contexts/cart'

export const metadata = {
  title: 'Ecommerce NextJs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} px-10 py-4`}>
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  )
}
